/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TimKiem;


import NhanVien.NhanVien;
import BangChamCong.BangChamCong;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import NhanVien.INhanVienDAO;
import BangChamCong.IBangChamCongDAO;

/**
 *
 * @author FPT
 */
public class frmTimKiem extends javax.swing.JPanel {

    private DefaultTableModel dtm;
    private DefaultTableModel dtmMark;
    

    /**
     * Creates new form TimKiem
     */
    public frmTimKiem() {
        initComponents();
        dtm = new DefaultTableModel();
        dtmMark = new DefaultTableModel();

        //TIm kiem theo mã phòng ban
        dtm.addColumn("Mã Nhân Viên");
        dtm.addColumn("Họ Tên");
        dtm.addColumn("CCCD");
        dtm.addColumn("Ngày Sinh");
        dtm.addColumn("Quê Quán");
        dtm.addColumn("Giới Tính");
        dtm.addColumn("Số ĐT");
        dtm.addColumn("Mã Phòng Ban");
        dtm.addColumn("Mã Chức Vụ");
        dtm.addColumn("Mã Khen Thưởng");
        jtbTTNV.setModel(dtm);
    
  

            dtmMark.addColumn("Mã Chấm công");
            dtmMark.addColumn("Mã Nhân Viên");
            dtmMark.addColumn("Tháng Chấm Công");
            dtmMark.addColumn("Năm Chấm Công");
            dtmMark.addColumn("Số ngày làm");
            dtmMark.addColumn("Số ngày nghỉ");
            dtmMark.addColumn("Số giờ tăng ca");
            jtbBangCC.setModel(dtmMark);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbTTNV = new javax.swing.JTable();
        jtfMaPB = new javax.swing.JTextField();
        jbtTimkiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jtfmanv = new javax.swing.JTextField();
        jbtnsearchmanv = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbBangCC = new javax.swing.JTable();

        jButton1.setText("jButton1");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        jtbTTNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ Tên", "CCCD", "Ngày Sinh", "Quê Quán", "Giới Tính", "Số Điện Thoại", "Mã Phòng Ban", "Mã Chức Vụ ", "Mã Khen Thưởng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbTTNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtbTTNVMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtbTTNV);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jtfMaPB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfMaPBKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfMaPBKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfMaPBKeyTyped(evt);
            }
        });

        jbtTimkiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtTimkiem.setForeground(new java.awt.Color(0, 0, 255));
        jbtTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search2.png"))); // NOI18N
        jbtTimkiem.setText("Tìm kiếm ");
        jbtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTimkiemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Nhập Mã Phòng Ban");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtfMaPB, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtTimkiem)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtTimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfMaPB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Tìm Nhân Viên Theo Mã Phòng Ban", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtfmanv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfmanvKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfmanvKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfmanvKeyTyped(evt);
            }
        });

        jbtnsearchmanv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnsearchmanv.setForeground(new java.awt.Color(0, 0, 255));
        jbtnsearchmanv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search2.png"))); // NOI18N
        jbtnsearchmanv.setText("Search");
        jbtnsearchmanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsearchmanvActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Nhập Mã Nhân Viên");

        jtbBangCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Chấm Công", "Mã Nhân Viên", "Tháng CC", "Năm CC", "Số ngày làm", "Số ngày nghỉ", "Số giờ tăng ca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbBangCC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtbBangCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtbBangCCMouseReleased(evt);
            }
        });
        jtbBangCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbBangCCKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jtbBangCC);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jtfmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnsearchmanv)
                .addContainerGap(223, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnsearchmanv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addGap(105, 105, 105)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 787, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Tìm Bảng Châm Công theo mã NV", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtbTTNVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTTNVMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbTTNVMouseReleased
    private static Object[] toObjectData(NhanVien nv) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String date = dateFormat.format(nv.getNgaySinh());

        boolean flag = nv.isGioitinh();
        String gioitinh = "Nam";
        if (!flag) {
            gioitinh = "Nữ";
        }
        Object[] objectData = {nv.getMaNV(), nv.getHoTen(),
                nv.getCCCD(), date, nv.getQueQuan (), gioitinh, nv.getSdtNV(), nv.getMaPB (),nv.getMaCV (),nv.getMaKT ()};
        return objectData;
    }

    public void timkiem() {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        String MaPB = jtfMaPB.getText();
        try {
            try {
                INhanVienDAO nhanVienDAO = (INhanVienDAO) Class.forName("NhanVien.NhanVienDAO").newInstance();
                ArrayList<NhanVien> list = nhanVienDAO.findByIDPhongban(MaPB);
                for (NhanVien nv : list) {
                    dtm.addRow(toObjectData(nv));
                }
            } catch (InstantiationException ex) {
                Logger.getLogger(TimKiem.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(TimKiem.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TimKiem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

  public void timKiemCC() {
        while (dtmMark.getRowCount() > 0) {
            dtmMark.removeRow(0);
        }
        try {

            String manv = jtfmanv.getText();
            IBangChamCongDAO bangChamCongDAO = (IBangChamCongDAO) Class.forName("BangChamCong.BangChamCongDAO").newInstance();
            ArrayList<BangChamCong> listbcc = bangChamCongDAO.findByIDNhanVien(manv);
            for (BangChamCong bcc : listbcc) {
                dtmMark.addRow(toObjectsData(bcc));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TimKiem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(TimKiem.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(TimKiem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static Object[] toObjectsData(BangChamCong bcc) {
        Object[] objectsData = {bcc.getMaChamCong(), bcc.getMaNV(), bcc.getThangCC(),
            bcc.getNamCC(),bcc.getSongaylam(),bcc.getSongaynghi(),bcc.getSogiotangca()};
        return objectsData;
    }
    private void jbtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTimkiemActionPerformed
        timkiem();
    }//GEN-LAST:event_jbtTimkiemActionPerformed

    private void jtfMaPBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMaPBKeyTyped
    }//GEN-LAST:event_jtfMaPBKeyTyped

    private void jtfMaPBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMaPBKeyReleased
        timkiem();
    }//GEN-LAST:event_jtfMaPBKeyReleased

    private void jtfMaPBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMaPBKeyPressed
        timkiem();
    }//GEN-LAST:event_jtfMaPBKeyPressed

    private void jtfmanvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmanvKeyPressed
       timKiemCC();
    }//GEN-LAST:event_jtfmanvKeyPressed

    private void jtfmanvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmanvKeyReleased
       timKiemCC();
    }//GEN-LAST:event_jtfmanvKeyReleased

    private void jtfmanvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmanvKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfmanvKeyTyped

    private void jbtnsearchmanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsearchmanvActionPerformed
       timKiemCC();
    }//GEN-LAST:event_jbtnsearchmanvActionPerformed

    private void jtbBangCCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbBangCCMouseReleased
       
    }//GEN-LAST:event_jtbBangCCMouseReleased

    private void jtbBangCCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbBangCCKeyReleased

    }//GEN-LAST:event_jtbBangCCKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtTimkiem;
    private javax.swing.JButton jbtnsearchmanv;
    private javax.swing.JTable jtbBangCC;
    private javax.swing.JTable jtbTTNV;
    private javax.swing.JTextField jtfMaPB;
    private javax.swing.JTextField jtfmanv;
    // End of variables declaration//GEN-END:variables
}
