/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package NhanVien;

import KiemTra.Kiemtra;
import Phongban.Phongban;
import ChucVu.ChucVu;
import MucKhenThuong.MucKhenThuong;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import Phongban.IPhongbanDAO;
import ChucVu.IChucVuDAO;
import MucKhenThuong.IMucKhenThuongDAO;
import javax.swing.DefaultButtonModel;
/**
 *
 * @author admin
 */
public class frmNhanVien extends javax.swing.JPanel {

    private DefaultTableModel dtm;
    private DefaultButtonModel dbm;
    private DefaultComboBoxModel dcbmMaPB;
    private DefaultComboBoxModel dcbmMaCV;
    private DefaultComboBoxModel dcbmMaKT;
    ArrayList<Phongban> listPB = null;
    ArrayList<ChucVu> listCV = null;
    ArrayList<MucKhenThuong> listKT = null; 
    ArrayList<NhanVien> list = null;
    public static String regexDDMMYYYY = "^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d$";

    public frmNhanVien() {
        try {
            initComponents();
            dtm = new DefaultTableModel();
            dcbmMaPB = new DefaultComboBoxModel();
            dcbmMaCV = new DefaultComboBoxModel();
            dcbmMaKT = new DefaultComboBoxModel();
            dbm = new DefaultButtonModel();
            
            IPhongbanDAO phongbanDAO = (IPhongbanDAO) Class.forName("Phongban.PhongbanDAO").newInstance();
            listPB = phongbanDAO.getAll();
            for (Phongban pb : listPB) {
                dcbmMaPB.addElement(pb.getMaPB());
            }
            jcbMaPB.setModel(dcbmMaPB);
            
            
            IChucVuDAO chucVuDAO = (IChucVuDAO) Class.forName("ChucVu.ChucVuDAO").newInstance();
            listCV = chucVuDAO.getAll();
            for (ChucVu cv : listCV) {
                dcbmMaCV.addElement(cv.getMaCV());
            }
            jcbMaCV.setModel(dcbmMaCV);
            
            {
            IMucKhenThuongDAO muckhenThuongDAO = (IMucKhenThuongDAO) Class.forName("MucKhenThuong.MucKhenThuongDAO").newInstance();
            listKT = muckhenThuongDAO.getAll();
            for (MucKhenThuong kt : listKT) {
                dcbmMaKT.addElement(kt.getMaKT());
            }
            jcbMaKT.setModel(dcbmMaKT);
            }
           
            

            dtm.addColumn("Mã Nhân Viên");
            dtm.addColumn("Họ Tên");
            dtm.addColumn("CCCD");
            dtm.addColumn("Ngày Sinh");
            dtm.addColumn("Quê Quán");
            dtm.addColumn("Giới Tính");
            dtm.addColumn("Số ĐT");
            dtm.addColumn("Mã Phòng Ban");
            dtm.addColumn("Mã Chức Vụ");
            dtm.addColumn("Mã Mức Khen Thưởng");
            loaddata();
        } catch (InstantiationException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfMaNV = new javax.swing.JTextField();
        jtfHoTen = new javax.swing.JTextField();
        jcbMaPB = new javax.swing.JComboBox();
        jtfCCCD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfDienThoai = new javax.swing.JTextField();
        jrbsex = new javax.swing.JRadioButton();
        jtfQueQuan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfngaysinh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcbMaKT = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jcbMaCV = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbTTNV = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jbAdd = new javax.swing.JButton();
        jbUpdate = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Mã Phòng Ban");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Mã Nhân Viên");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Họ Tên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("CCCD");

        jcbMaPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaPBActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Số Điện Thoại");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Giới Tính");

        jrbsex.setText("Nam/Nữ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Quê Quán");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Ngày Sinh");

        jLabel9.setText("(dd/MM/yyyy)");

        jcbMaKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaKTActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Mã Chức Vụ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Mã Khen Thưởng");

        jcbMaCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaCVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtfngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbMaPB, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jcbMaKT, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel6)
                        .addGap(49, 49, 49)
                        .addComponent(jrbsex)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jrbsex)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jtfDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jcbMaPB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jtfngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jcbMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbMaKT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addContainerGap(170, Short.MAX_VALUE))))
        );

        jtbTTNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ Tên", "CCCD", "Ngày Sinh", "Quê Quán", "Giới Tính", "Số Điện Thoại", "Mã Phòng Ban", "Mã Chức Vụ", "Mã Khen Thưởng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbTTNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtbTTNVMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtbTTNV);
        if (jtbTTNV.getColumnModel().getColumnCount() > 0) {
            jtbTTNV.getColumnModel().getColumn(9).setHeaderValue("Mã Khen Thưởng");
        }

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        jbAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAdd.setForeground(new java.awt.Color(0, 102, 102));
        jbAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add.png"))); // NOI18N
        jbAdd.setText("Thêm");
        jbAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jbUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbUpdate.setForeground(new java.awt.Color(0, 102, 102));
        jbUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/45.png"))); // NOI18N
        jbUpdate.setText("Cập nhật");
        jbUpdate.setEnabled(false);
        jbUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateActionPerformed(evt);
            }
        });

        jbDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbDelete.setForeground(new java.awt.Color(255, 0, 0));
        jbDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        jbDelete.setText("Xóa");
        jbDelete.setEnabled(false);
        jbDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbDelete.setIconTextGap(2);
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });

        jbExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbExit.setForeground(new java.awt.Color(0, 102, 102));
        jbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reload.png"))); // NOI18N
        jbExit.setText("Tải lại");
        jbExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbUpdate)
                    .addComponent(jbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbAdd, jbDelete, jbExit, jbUpdate});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbAdd, jbDelete, jbExit, jbUpdate});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 0, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setForeground(new java.awt.Color(204, 204, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("THÔNG TIN NHÂN VIÊN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(274, 274, 274))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loaddata() {
        try {
            INhanVienDAO nhanVienDAO = (INhanVienDAO) Class.forName("NhanVien.NhanVienDAO").newInstance();
            list = new NhanVienDAO().getAll();
            for (NhanVien sv : list) {
                dtm.addRow(toObjectData(sv));
            }
            jtbTTNV.setModel(dtm);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jtbTTNVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTTNVMouseReleased
        // TODO add your handling code here:
        jtfMaNV.setText(jtbTTNV.getValueAt(jtbTTNV.getSelectedRow(), 0).toString());
        jtfHoTen.setText(jtbTTNV.getValueAt(jtbTTNV.getSelectedRow(), 1).toString());
        jcbMaPB.setSelectedItem(jtbTTNV.getValueAt(jtbTTNV.getSelectedRow(), 7).toString());
        jcbMaCV.setSelectedItem(jtbTTNV.getValueAt(jtbTTNV.getSelectedRow(), 8).toString());
        jcbMaKT.setSelectedItem(jtbTTNV.getValueAt(jtbTTNV.getSelectedRow(), 9).toString());
        jtfCCCD.setText(jtbTTNV.getValueAt(jtbTTNV.getSelectedRow(), 2).toString());
        jtfngaysinh.setText(jtbTTNV.getValueAt(jtbTTNV.getSelectedRow(), 3).toString());
        jtfQueQuan.setText(jtbTTNV.getValueAt(jtbTTNV.getSelectedRow(), 4).toString());
        jtfDienThoai.setText(jtbTTNV.getValueAt(jtbTTNV.getSelectedRow(), 6).toString());
        String sex = jtbTTNV.getValueAt(jtbTTNV.getSelectedRow(), 5).toString();
        if (sex.equals("true")) {
            jrbsex.setSelected(true);
        } else {
            jrbsex.setSelected(false);
        }
        jbAdd.setEnabled(false);
        jbUpdate.setEnabled(true);
        jbDelete.setEnabled(true);
        jtfMaNV.setEnabled(false);
//        jcbMaPB.setEnabled(false);
//        jcbMaCV.setEnabled(false);
//        jcbMaKT.setEnabled(false);
    }//GEN-LAST:event_jtbTTNVMouseReleased

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        String MaNV  = jtfMaNV.getText();
        String HoTen = jtfHoTen.getText();
        String CCCD = jtfCCCD.getText();
        String NgaySinh = jtfngaysinh.getText();
        String QueQuan = jtfQueQuan.getText();
        boolean GioiTinh = jrbsex.isSelected();
        // String ngaysinh = jdate.getDateFormatString();
        // String strPattern = "[^a-z ]";
        String SdtNV = jtfDienThoai.getText();
        String MaPB = listPB.get(jcbMaPB.getSelectedIndex()).getMaPB();
        String MaCV = listCV.get(jcbMaCV.getSelectedIndex()).getMaCV();
        String MaKT = listKT.get(jcbMaKT.getSelectedIndex()).getMaKT();

        Kiemtra c = new Kiemtra();
        if (!checkinfo()) {
            return;
        }


        Date d = null;
        if (NgaySinh == null || NgaySinh.equals("") || !NgaySinh.matches(regexDDMMYYYY)) {
            JOptionPane.showMessageDialog(this, "Lỗi ngày sinh", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            // JOptionPane.showMessageDialog(null, "Lỗi ngày sinh");
            jtfngaysinh.setText("");
            jtfngaysinh.requestFocus();
            return;
        } else {
            try {
                d = new SimpleDateFormat("dd/MM/yyyy").parse(NgaySinh);
            } catch (ParseException ex) {
                Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                return;
            }
        }
        NhanVien nhanVien = new NhanVien(MaNV, HoTen, CCCD,d,QueQuan, GioiTinh, SdtNV, MaPB,MaCV,MaKT);
        ArrayList<NhanVien> listCheck = new NhanVienDAO().CheckID(MaNV);
        if (listCheck.size() > 0) {
            JOptionPane.showMessageDialog(this, "Mã ID bị trùng. Vui lòng kiểm tra lại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            jtfMaNV.setText("");
            jtfMaNV.requestFocus();
        } else {

            NhanVien insert = new NhanVienDAO().addNew(nhanVien);

            if (insert != null) {

                showAll();
            }
        }

//        else{
//        JOptionPane.showMessageDialog(this, "Mã ID bị trùng", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_jbAddActionPerformed

    private void jbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateActionPerformed
        String MaNV  = jtfMaNV.getText();
        String HoTen = jtfHoTen.getText();
        String CCCD = jtfCCCD.getText();
        String NgaySinh = jtfngaysinh.getText();
        String QueQuan = jtfQueQuan.getText();
        boolean GioiTinh = jrbsex.isSelected();
        // String ngaysinh = jdate.getDateFormatString();
        // String strPattern = "[^a-z ]";
        String SdtNV = jtfDienThoai.getText();
        String MaPB = listPB.get(jcbMaPB.getSelectedIndex()).getMaPB();
        String MaCV = listCV.get(jcbMaCV.getSelectedIndex()).getMaCV();
        String MaKT = listKT.get(jcbMaKT.getSelectedIndex()).getMaKT();


        Kiemtra c = new Kiemtra();
        if (!checkinfo()) {
            return;
        }

        Date d = null;
        if (NgaySinh == null || NgaySinh.equals("") || !NgaySinh.matches(regexDDMMYYYY)) {
            JOptionPane.showMessageDialog(this, "Lỗi ngày sinh", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            // JOptionPane.showMessageDialog(null, "Lỗi ngày sinh");
            jtfngaysinh.setText("");
            jtfngaysinh.requestFocus();
            return;
        } else {
            try {
                d = new SimpleDateFormat("dd/MM/yyyy").parse(NgaySinh);
            } catch (ParseException ex) {
                Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
                return;
            }
        }

        NhanVien nhanVien = new NhanVien(MaNV, HoTen, CCCD,d,QueQuan, GioiTinh, SdtNV, MaPB,MaCV,MaKT);
        NhanVien updateByID = new NhanVienDAO().updateByID(nhanVien);
        if (updateByID != null) {
            showAll();
        }
        jbAdd.setEnabled(true);
        jbUpdate.setEnabled(false);
        jbDelete.setEnabled(false);
        jtfMaNV.setEnabled(true);
//        jcbMaPB.setEnabled(true);
//        jcbMaCV.setEnabled(true);
//        jcbMaKT.setEnabled(true);

    }//GEN-LAST:event_jbUpdateActionPerformed
    private static Object[] toObjectData(NhanVien nv) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String date = dateFormat.format(nv.getNgaySinh());

        boolean flag = nv.isGioitinh();
        String gioitinh = "Nam";
        if (!flag) {
            gioitinh = "Nữ";
        }
        Object[] objectData = {nv.getMaNV(), nv.getHoTen(),
                nv.getCCCD(), date, nv.getQueQuan (), gioitinh, nv.getSdtNV(), nv.getMaPB (),nv.getMaCV (),nv.getMaKT ()};
        return objectData;
    }
    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa dữ liệu này?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            try {

                String MaNV = jtfMaNV.getText();
                new NhanVienDAO().deleteIDNhanVien(MaNV);
            } catch (SQLException ex) {
                  JOptionPane.showMessageDialog(this, "Nhân viên này có luong, hãy xóa luong của sinh viên này trước", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException ex) {
                  JOptionPane.showMessageDialog(this, "Nhân viên này có luong, hãy xóa luong của sinh viên này trước", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);

            }
            loaddata();
            resetForm();
            jbAdd.setEnabled(true);
            jbUpdate.setEnabled(false);
            jbDelete.setEnabled(false);
            jtfMaNV.setEnabled(true);
//            jcbMaPB.setEnabled(true);
//        jcbMaCV.setEnabled(true);
//        jcbMaKT.setEnabled(true);
        }
    }//GEN-LAST:event_jbDeleteActionPerformed
    public void resetForm() {
        jtfMaNV.setText("");
        jtfHoTen.setText("");
        jtfDienThoai.setText("");
        jtfQueQuan.setText("");
        jtfCCCD.setText("");
        jtfngaysinh.setText("");
        jtfMaNV.requestFocus();
    }

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        this.resetForm();
    }//GEN-LAST:event_jbExitActionPerformed

    private void jcbMaPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaPBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMaPBActionPerformed

    private void jcbMaCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMaCVActionPerformed

    private void jcbMaKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaKTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMaKTActionPerformed
    private void showAll() {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);

        }
        int selectedIndex = jcbMaPB.getSelectedIndex();
        Phongban getPhongban = listPB.get(selectedIndex);
        ArrayList<NhanVien> nvs = new NhanVienDAO().findByIDPhongban(getPhongban.getMaPB());
            //ArrayList<SinhVien> sinhViens = new SinhVienDAO().CheckID(g)
            for (NhanVien nv : nvs) {
                Vector vector = new Vector();
                vector.add(nv.getMaNV());
                vector.add(nv.getHoTen());
                vector.add(nv.getCCCD());
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                vector.add(dateFormat.format(nv.getNgaySinh()));
                vector.add(nv.getQueQuan());
                // vector.add(sv.isGioitinh());
                if (nv.isGioitinh() == true) {
                    vector.add("Nam");
                } else {
                    vector.add("Nữ");
                }
                vector.add(nv.getSdtNV());
                vector.add(nv.getMaPB());
                vector.add(nv.getMaCV());
                vector.add(nv.getMaKT());
                dtm.addRow(vector);

            }
            resetForm();
    }

    public boolean checkinfo() {
        Kiemtra c = new Kiemtra();
        if (!c.checkID(jtfMaNV.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập mã sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfMaNV.setText("");
            jtfMaNV.requestFocus();
            return false;
        } else if (!c.checkSpace(jtfHoTen.getText()) || !c.check(jtfHoTen.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập tên sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfHoTen.setText("");
            jtfHoTen.requestFocus();
            return false;

        } else if (!c.checkSpace(jtfCCCD.getText()) || !c.check(jtfCCCD.getText())) {
            JOptionPane.showMessageDialog(this, "Kiểm tra lại nhập CCCD", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfCCCD.setText("");
            jtfCCCD.requestFocus();
            return false;

//        } else if (!c.checkSpace(jtfngaysinh.getText())|| !c.check(jtfHeDaoTao.getText()) || !c.checkDate(jtfngaysinh.getText())) {
//            JOptionPane.showMessageDialog(this, "Kiểm tra lại ngày sinh", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
//            jtfngaysinh.setText("");
//            jtfngaysinh.requestFocus();
//            return false;

        } else if (!c.checkSpace(jtfQueQuan.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập địa chỉ sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfQueQuan.setText("");
            jtfQueQuan.requestFocus();
            return false;

        } else if (!c.checkSpace(jtfDienThoai.getText()) || !c.checkPhone(jtfDienThoai.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập phone sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfDienThoai.setText("");
            jtfDienThoai.requestFocus();
            return false;
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbUpdate;
    private javax.swing.JComboBox jcbMaCV;
    private javax.swing.JComboBox jcbMaKT;
    private javax.swing.JComboBox jcbMaPB;
    private javax.swing.JRadioButton jrbsex;
    private javax.swing.JTable jtbTTNV;
    private javax.swing.JTextField jtfCCCD;
    private javax.swing.JTextField jtfDienThoai;
    private javax.swing.JTextField jtfHoTen;
    private javax.swing.JTextField jtfMaNV;
    private javax.swing.JTextField jtfQueQuan;
    private javax.swing.JTextField jtfngaysinh;
    // End of variables declaration//GEN-END:variables
}
