/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Luong;

import NhanVien.*;
import KiemTra.Kiemtra;
import NhanVien.NhanVien;
import BangChamCong.BangChamCong;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import NhanVien.INhanVienDAO;
import BangChamCong.IBangChamCongDAO;
import javax.swing.DefaultButtonModel;
/**
 *
 * @author admin
 */
public class frmLuong extends javax.swing.JPanel {

     private DefaultTableModel dtm;
    private DefaultButtonModel dbm;
    private DefaultComboBoxModel dcbmMaNV;
    private DefaultComboBoxModel dcbmMaChamCong;
    ArrayList<NhanVien> listNV = null;
    ArrayList<BangChamCong> listCC = null;
    ArrayList<Luong> list = null;


    public frmLuong() {
        try {
            initComponents();
             dtm = new DefaultTableModel();
            dcbmMaNV = new DefaultComboBoxModel();
            dcbmMaChamCong = new DefaultComboBoxModel();
           
            dbm = new DefaultButtonModel();
            
            INhanVienDAO nhanviennDAO = (INhanVienDAO) Class.forName("NhanVien.NhanVienDAO").newInstance();
            listNV = nhanviennDAO.getAll();
            for (NhanVien nv : listNV) {
                dcbmMaNV.addElement(nv.getMaNV());
            }
            jcbMaNV.setModel(dcbmMaNV);

            
            
            IBangChamCongDAO bangChamCongDAO = (IBangChamCongDAO) Class.forName("BangChamCong.BangChamCongDAO").newInstance();
            listCC = bangChamCongDAO.getAll();
            for (BangChamCong bcc : listCC) {
                dcbmMaChamCong.addElement(bcc.getMaChamCong());
            }
            jcbMaChamCong.setModel(dcbmMaChamCong);
            
            

            dtm.addColumn("Mã Lương");
            dtm.addColumn("Mã Nhân Viên");
            dtm.addColumn("Mã Chấm Công");
             dtm.addColumn("Tháng Lương");
            dtm.addColumn("Năm Lương");
            dtm.addColumn("Lương Cơ Bản");
            dtm.addColumn("Phụ Cấp");
            dtm.addColumn("Lương Tăng Ca");
            dtm.addColumn("BHTN");
            dtm.addColumn("BHYT");
            dtm.addColumn("BHXH");
            dtm.addColumn("Số Người Phụ Thuộc");
            dtm.addColumn("Thuế TNCN");
            dtm.addColumn("Lương Thực Lĩnh");
            loaddata();
        } catch (InstantiationException ex) {
            Logger.getLogger(frmLuong.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmLuong.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmLuong.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbTTL = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfMaLuong = new javax.swing.JTextField();
        jtfNamLuong = new javax.swing.JTextField();
        jcbMaNV = new javax.swing.JComboBox();
        jtfThangLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfPhuCap = new javax.swing.JTextField();
        jtfLuongTangCa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfLuongCoBan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jcbMaChamCong = new javax.swing.JComboBox();
        jtfBHYT = new javax.swing.JTextField();
        jtfBHTN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtfBHXH = new javax.swing.JTextField();
        jtfLuongThucLinh = new javax.swing.JTextField();
        jtfThueTNCN = new javax.swing.JTextField();
        jtfSoNguoiPT = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbAdd = new javax.swing.JButton();
        jbUpdate = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setPreferredSize(new java.awt.Dimension(2000, 600));

        jPanel1.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2125, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 0, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setForeground(new java.awt.Color(204, 204, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("THÔNG TIN LƯƠNG");

        jtbTTL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Lương", "Mã NV", "Mã CC", "Tháng ", "Năm", "Lương CB", "Phụ Cấp", "Lương TC", "BHTN", "BHYT", "BHXH", "Số Người PT", "Thuế TNCN", "Lương Thực Lĩnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbTTL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtbTTLMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtbTTL);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Mã Nhân Viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Mã Lương");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Tháng Lương");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Năm Lương");

        jcbMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaNVActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Phụ Cấp");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Lương Cơ Bản");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Mã Chấm Công");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("BHYT");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Lương Tăng Ca");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("BHTN");

        jcbMaChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaChamCongActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("BHXH");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Số Người PT");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Thuế TNCN");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Lương Thực Lĩnh");

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        jbAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAdd.setForeground(new java.awt.Color(0, 102, 102));
        jbAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add.png"))); // NOI18N
        jbAdd.setText("Thêm");
        jbAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddActionPerformed(evt);
            }
        });

        jbUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbUpdate.setForeground(new java.awt.Color(0, 102, 102));
        jbUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/45.png"))); // NOI18N
        jbUpdate.setText("Cập nhật");
        jbUpdate.setEnabled(false);
        jbUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateActionPerformed(evt);
            }
        });

        jbDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbDelete.setForeground(new java.awt.Color(255, 0, 0));
        jbDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        jbDelete.setText("Xóa");
        jbDelete.setEnabled(false);
        jbDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbDelete.setIconTextGap(2);
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });

        jbExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbExit.setForeground(new java.awt.Color(0, 102, 102));
        jbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reload.png"))); // NOI18N
        jbExit.setText("Tải lại");
        jbExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbUpdate)
                    .addComponent(jbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbAdd, jbDelete, jbExit, jbUpdate});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbAdd, jbDelete, jbExit, jbUpdate});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtfThangLuong)
                    .addComponent(jcbMaNV, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfMaLuong, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbMaChamCong, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfNamLuong))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtfLuongTangCa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtfPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfLuongCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfBHTN, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfBHYT, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfSoNguoiPT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jtfThueTNCN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfLuongThucLinh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfBHXH))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfMaLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jtfLuongCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jtfBHXH, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel4)
                        .addComponent(jtfPhuCap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jtfSoNguoiPT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcbMaChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtfThangLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfNamLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfLuongTangCa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jtfThueTNCN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfBHTN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jtfLuongThucLinh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfBHYT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(415, 415, 415)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(674, 674, 674)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loaddata() {
        try {
            ILuongDAO luongDAO = (ILuongDAO) Class.forName("Luong.LuongDAO").newInstance();
            list = new LuongDAO().getAll();
            for (Luong lu : list) {
                dtm.addRow(toObjectsData(lu));
            }
            jtbTTL.setModel(dtm);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmLuong.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmLuong.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmLuong.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jtbTTLMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTTLMouseReleased
        // TODO add your handling code here:
        jtfMaLuong.setText(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 0).toString());
        jcbMaNV.setSelectedItem(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 1).toString());
        jcbMaChamCong.setSelectedItem(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 2).toString());
        jtfThangLuong.setText(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 3).toString());
        jtfNamLuong.setText(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 4).toString());
       jtfLuongCoBan.setText(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 5).toString());
        jtfPhuCap.setText(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 6).toString());
        jtfLuongTangCa.setText(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 7).toString());
        jtfBHTN.setText(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 8).toString());
       jtfBHYT.setText(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 9).toString());
        jtfBHXH.setText(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 10).toString());
        jtfSoNguoiPT.setText(jtbTTL.getValueAt(jtbTTL.getSelectedRow(),11).toString());
        jtfThueTNCN.setText(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 12).toString());
        jtfLuongThucLinh.setText(jtbTTL.getValueAt(jtbTTL.getSelectedRow(), 13).toString());
        
        jbAdd.setEnabled(false);
        jbUpdate.setEnabled(true);
        jbDelete.setEnabled(true);
        jtfMaLuong.setEnabled(false);
//        
    }//GEN-LAST:event_jtbTTLMouseReleased

    private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddActionPerformed
        String MaLuong  = jtfMaLuong.getText();
        String MaNV = listNV.get(jcbMaNV.getSelectedIndex()).getMaNV();
        String MaChamCong = listCC.get(jcbMaChamCong.getSelectedIndex()).getMaChamCong();
        String ThangLuong = jtfThangLuong.getText();
        String NamLuong = jtfNamLuong.getText();
        String LuongCoBan = jtfLuongCoBan.getText();
         String PhuCap = jtfPhuCap.getText();
        String LuongTangCa = jtfLuongTangCa.getText();
        String BHTN = jtfBHTN.getText();
        String BHYT = jtfBHYT.getText();
        String BHXH = jtfBHXH.getText();
        String SoNguoiPT = jtfSoNguoiPT.getText();
        String ThueTNCN = jtfThueTNCN.getText();
        String LuongThucLinh = jtfLuongThucLinh.getText();
        
    
        Kiemtra c = new Kiemtra();
        if (!checkinfo()) {
            return;
        }

        int tl,nl,snpt;
        tl = Integer.parseInt(ThangLuong);
        nl= Integer.parseInt(NamLuong);
        snpt= Integer.parseInt(SoNguoiPT);
        
        float lcb,pc,ltc,bhtn,bhyt,bhxh,ttncn,ltl;
        lcb=Float.parseFloat(LuongCoBan);
        pc=Float.parseFloat(PhuCap);
        ltc=Float.parseFloat(LuongTangCa);
        bhtn=Float.parseFloat(BHTN);
        bhyt=Float.parseFloat(BHYT);
        bhxh=Float.parseFloat(BHXH);
        ttncn=Float.parseFloat(ThueTNCN);
        ltl=Float.parseFloat(LuongThucLinh);
        
        Luong luong = new Luong(MaLuong, MaNV,MaChamCong,tl,nl, lcb, pc, ltc, bhtn, bhyt,bhxh,snpt,ttncn,ltl);
        ArrayList<Luong> listCheck = new LuongDAO().CheckID(MaLuong);
        if (listCheck.size() > 0) {
            JOptionPane.showMessageDialog(this, "Mã ID bị trùng", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
            jtfMaLuong.setText("");
            jtfMaLuong.requestFocus();

        } else {
            Luong insert = new LuongDAO().addNew(luong);
            if (insert != null) {
                showAll();
            }
        }


//        else{
//        JOptionPane.showMessageDialog(this, "Mã ID bị trùng", "vui lòng kiểm tra lại", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_jbAddActionPerformed

    private void jbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateActionPerformed
       String MaLuong  = jtfMaLuong.getText();
        String ThangLuong = jtfThangLuong.getText();
        String NamLuong = jtfNamLuong.getText();
        String MaNV = listNV.get(jcbMaNV.getSelectedIndex()).getMaNV();
        String MaChamCong = listCC.get(jcbMaChamCong.getSelectedIndex()).getMaChamCong();
        String LuongCoBan = jtfLuongCoBan.getText();
         String PhuCap = jtfPhuCap.getText();
        String LuongTangCa = jtfLuongTangCa.getText();
        String BHTN = jtfBHTN.getText();
        String BHYT = jtfBHYT.getText();
        String BHXH = jtfBHXH.getText();
        String SoNguoiPT = jtfSoNguoiPT.getText();
        String ThueTNCN = jtfThueTNCN.getText();
        String LuongThucLinh = jtfLuongThucLinh.getText();
        
    
        Kiemtra c = new Kiemtra();
        if (!checkinfo()) {
            return;
        }

        int tl,nl,snpt;
        tl = Integer.parseInt(ThangLuong);
        nl= Integer.parseInt(NamLuong);
        snpt= Integer.parseInt(SoNguoiPT);
        
        float lcb,pc,ltc,bhtn,bhyt,bhxh,ttncn,ltl;
        lcb=Float.parseFloat(LuongCoBan);
        pc=Float.parseFloat(PhuCap);
        ltc=Float.parseFloat(LuongTangCa);
        bhtn=Float.parseFloat(BHTN);
        bhyt=Float.parseFloat(BHYT);
        bhxh=Float.parseFloat(BHXH);
        ttncn=Float.parseFloat(ThueTNCN);
        ltl=Float.parseFloat(LuongThucLinh);
        
        Luong luong = new Luong(MaLuong,MaNV,MaChamCong,tl,nl, lcb, pc, ltc, bhtn, bhyt,bhxh,snpt,ttncn,ltl);
        Luong update = new LuongDAO().updateByID(luong);
        if (update != null) {
            showAll();
        }
        jbAdd.setEnabled(true);
        jbUpdate.setEnabled(false);
        jbDelete.setEnabled(false);
        jtfMaLuong.setEnabled(true);
//        jcbMaPB.setEnabled(true);
//        jcbMaCV.setEnabled(true);
//        jcbMaKT.setEnabled(true);

    }//GEN-LAST:event_jbUpdateActionPerformed
    public static Object[] toObjectsData(Luong lu) {
        Object[] objectsData = {lu.getMaLuong(), lu.getMaNV(), lu.getMaChamCong(),
            lu.getThangLuong(),lu.getNamLuong(),lu.getLuongCoBan(),lu.getPhuCap(),lu.getLuongTangCa(), lu.getBHTN(), lu.getBHYT(),
            lu.getBHXH(),lu.getSoNguoiPT(),lu.getThueTNCN(),lu.getLuongThucLinh()};
        return objectsData;
    }
    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa dữ liệu này?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            try {

                String MaLuong = jtfMaLuong.getText();
                new LuongDAO().deleteIDLuong(MaLuong);
            } catch (SQLException ex) {
                  JOptionPane.showMessageDialog(this, "Nhân viên này có luong, hãy xóa luong của sinh viên này trước", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException ex) {
                  JOptionPane.showMessageDialog(this, "Nhân viên này có luong, hãy xóa luong của sinh viên này trước", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);

            }
            loaddata();
            resetForm();
            jbAdd.setEnabled(true);
            jbUpdate.setEnabled(false);
            jbDelete.setEnabled(false);
            jtfMaLuong.setEnabled(true);
//            jcbMaPB.setEnabled(true);
//        jcbMaCV.setEnabled(true);
//        jcbMaKT.setEnabled(true);
        }
    }//GEN-LAST:event_jbDeleteActionPerformed
    public void resetForm() {
        jtfMaLuong.setText("");
        jtfThangLuong.setText("");
        jtfNamLuong.setText("");
        jtfLuongCoBan.setText("");
        jtfPhuCap.setText("");
        jtfLuongTangCa.setText("");
        jtfBHTN.setText("");
        jtfBHYT.setText("");
        jtfBHXH.setText("");
        jtfSoNguoiPT.setText("");
        jtfThueTNCN.setText("");
        jtfLuongThucLinh.setText("");
        jtfMaLuong.requestFocus();
    }

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        this.resetForm();
    }//GEN-LAST:event_jbExitActionPerformed

    private void jcbMaChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaChamCongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMaChamCongActionPerformed

    private void jcbMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMaNVActionPerformed
    private void showAll() {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        ArrayList<Luong> kts = new LuongDAO().getAll();
        for (Luong kt : kts) {
            Vector v = new Vector();
            v.add(kt.getMaLuong());
            v.add(kt.getThangLuong());
            v.add(kt.getNamLuong());
            v.add(kt.getLuongCoBan());
            v.add(kt.getPhuCap());
            v.add(kt.getLuongTangCa());
            v.add(kt.getBHXH());
            v.add(kt.getBHYT());
            v.add(kt.getBHTN());
            v.add(kt.getSoNguoiPT());
            v.add(kt.getThueTNCN());
            v.add(kt.getLuongThucLinh());

            dtm.addRow(v);
        }
        resetForm();
        // jtfthi.setText("");
    }

    public boolean checkinfo() {
        Kiemtra c = new Kiemtra();
        if (!c.checkID(jtfMaLuong.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập mã sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfMaLuong.setText("");
            jtfMaLuong.requestFocus();
            return false;
        } else if (!c.checkSpace(jtfThangLuong.getText()) || !c.check(jtfThangLuong.getText())) {
            JOptionPane.showMessageDialog(this, "Kiểm tra lại nhập tháng lương", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfThangLuong.setText("");
            jtfThangLuong.requestFocus();
            return false;

        } else if (!c.checkSpace(jtfNamLuong.getText()) || !c.check(jtfNamLuong.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập năm sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfNamLuong.setText("");
            jtfNamLuong.requestFocus();
            return false;



        } else if (!c.checkSpace(jtfLuongCoBan.getText()) || !c.check(jtfLuongCoBan.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfLuongCoBan.setText("");
            jtfLuongCoBan.requestFocus();
            return false;}
        else if (!c.checkSpace(jtfPhuCap.getText()) || !c.check(jtfPhuCap.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfPhuCap.setText("");
            jtfPhuCap.requestFocus();
            return false;}
        else if (!c.checkSpace(jtfLuongTangCa.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfLuongTangCa.setText("");
            jtfLuongTangCa.requestFocus();
            return false;
        }else if (!c.checkSpace(jtfBHTN.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfBHTN.setText("");
            jtfBHTN.requestFocus();
            return false;}
        else if (!c.checkSpace(jtfBHYT.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfBHYT.setText("");
            jtfBHYT.requestFocus();
            return false;}
        else if (!c.checkSpace(jtfBHXH.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfBHXH.setText("");
            jtfBHXH.requestFocus();
            return false;}
        else if (!c.checkSpace(jtfSoNguoiPT.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfSoNguoiPT.setText("");
            jtfSoNguoiPT.requestFocus();
            return false;}
        else if (!c.checkSpace(jtfThueTNCN.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfThueTNCN.setText("");
            jtfThueTNCN.requestFocus();
            return false;}
        else if (!c.checkSpace(jtfLuongThucLinh.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập sai", "Hãy nhập lại", JOptionPane.ERROR_MESSAGE);
            jtfLuongThucLinh.setText("");
            jtfLuongThucLinh.requestFocus();
            return false;}
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAdd;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbUpdate;
    private javax.swing.JComboBox jcbMaChamCong;
    private javax.swing.JComboBox jcbMaNV;
    private javax.swing.JTable jtbTTL;
    private javax.swing.JTextField jtfBHTN;
    private javax.swing.JTextField jtfBHXH;
    private javax.swing.JTextField jtfBHYT;
    private javax.swing.JTextField jtfLuongCoBan;
    private javax.swing.JTextField jtfLuongTangCa;
    private javax.swing.JTextField jtfLuongThucLinh;
    private javax.swing.JTextField jtfMaLuong;
    private javax.swing.JTextField jtfNamLuong;
    private javax.swing.JTextField jtfPhuCap;
    private javax.swing.JTextField jtfSoNguoiPT;
    private javax.swing.JTextField jtfThangLuong;
    private javax.swing.JTextField jtfThueTNCN;
    // End of variables declaration//GEN-END:variables
}
